### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Dagic-zewdu** [Sboursen/My-portfolio#17]
**In this session we raised an issue**

- we see the spy scroller is not working. please kindly, work on when you switch from different media width 
- Optional suggestion-it will be more accessible not to blur the navbar when you scroll down.
- we believe the user will have UX if you add a button that leads to the navbar when you scroll down to the bottom.

**Comment by Sboursen** [comment]
**Thank you for taking the time to give me feedback on the portfolio.**

> _The following issues were successfully dealt with:_
> - [x] The spy scroller works even after switching back and forth from the desktop version.
> - [x] Optional suggestion-it will be more accessible not to blur the navbar when you scroll down.
> - [x] I added a floating bottom that can take the user up to the top of the page. **Greater UX**

Please feel free to contribute with any more issues!!!
